version: "3"
services:
  app:
    build:
      context: node
    volumes:
      - ./node/src:/usr/src/app/src
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm run dev
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
  db:
    image: mysql
    command: --innodb-use-native-aio=0
    restart: on-failure
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
